### ISSUE TITLE
Error when trying to authenticate

### ISSUE THREAD

**Issue by dodontommy** [VvanGemert/omniauth-onedrive#1]
I am getting an error when trying to authenticate using this strategy. Everything seems to matchup to Microsoft's documentation but I when I try to hit the auth route I am greeted with this screen: 

![screen shot 2017-01-02 at 6 36 08 pm](https://cloud.githubusercontent.com/assets/6452091/21624018/bf116a0e-d1ca-11e6-89c8-c65f6ea3d432.png)

Which doesn't tell me much. The URL, however, contains a bit more information: 

`https://login.live.com/err.srf?lc=1033#error=invalid_request&error_description=The+provided+value+for+the+input+parameter+'redirect_uri'+is+not+valid.+The+expected+value+is+'https://login.live.com/oauth20_desktop.srf'+or+a+URL+which+matches+the+redirect+URI+registered+for+this+client+application.&state=ddfdd0432fed588eb0196ded394722b7fe5df14ff379c650`

According to the error message in the URL, my `redirect_uri` that I pass in the client options doesn't match one that I have defined in my created app, even though I've double and triple checked that it is the same URL.

Any ideas?

**Comment by prakashvi-dev1992** [comment]
I also get this type of error you need do add Redirect URIs in "https://apps.dev.microsoft.com"  accounts.
go through above link and click on app -> add platform and then add specific URI.
![redirect_uri](https://cloud.githubusercontent.com/assets/22785839/21634359/a8a72666-d27c-11e6-96c2-51f2c48b49fb.png)

i hope it will be help you.

**Comment by VvanGemert** [comment]
Thanks @prakashvi-dev1992 for solving this issue. I've updated the readme with these installation requirements. Please create a new issue of problems persist.
